---
#- paramLabel: MaxLength
#  name: MaxLengthProcessor
#  type: Long
#  description: Max length of the words
#  class: com.lumera.wordsearch.processor.MaxLengthProcessor
cmdOptionConfigs:
- name: maxlength
  paramLabel: MaxLength
  type: java.lang.Long
  processorType: com.lumera.wordsearch.processor.MaxLengthProcessor
