---
#- paramLabel: MaxLength
#  name: MaxLengthProcessor
#  type: Long
#  description: Max length of the words
#  class: com.lumera.wordsearch.processor.MaxLengthProcessor
combineProcessorType: AND
cmdOptionConfigs:
- name: maxlength
  paramLabel: MaxLength
  optionValueType: java.lang.Long
  processorType: MAXLENGTH
  description: Max length of the words

- name: minlength
  paramLabel: MinLength
  optionValueType: java.lang.Long
  processorType: MINLENGTH
  description: Min length of the words

- name: startswith
  paramLabel: StartsWith
  optionValueType: java.lang.String
  processorType: STARTSWITH
  description: words must have this prefix

- name: endswith
  paramLabel: EndsWith
  optionValueType: java.lang.String
  processorType: ENDSWITH
  description: words must have this suffix

- name: containsonly
  paramLabel: ContainsOnly
  optionValueType: java.lang.String
  processorType: CONTAINSONLY
  description: words are only made up of characters in the input string

- name: class
  paramLabel: Class
  optionValueType: com.lumera.wordsearch.constant.WordClassOptions
  processorType: CLASS
  description: Class of word
  converterType: com.lumera.wordsearch.service.WordClassOptionsConverter
